name: EAS Build
on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      PROFILE:
        required: false
        type: string
        default: production
jobs:
  build:
      - name: Install and build
        runs-on: ubuntu-latest # SO en el que se ejecuta este job
      - uses: actions/checkout@v3 # graba lo cambios de nuestro repositorio a la maquina virtual del job
      - uses: actions/setup-node@v3 #instala node 16.x con npm, dentro de la maquina virtual
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7 # instala eas en la maquina virtual de este job
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }} # token que le damos a la MV y se conecte a nuestra cuenta de Expo
      - name: Install dependencies
       # run: npm ci # npm install
       ## uso yarn en lugar de npm
        run: npm ci      
        # |
        #   if [ -e yarn.lock ]; then
        #    yarn install --frozen-lockfile
        #   elif [ -e package-lock.json ]; then
        #    npm ci
        #   else
        #    npm i
        #   fi
      - name: Build on EAS
        run: eas build --profile ${{ inputs.PROFILE }} --platform  ${{ inputs.PLATFORM }}  --non-interactive # para el staging
